/**
 * P1.5-W04A — Ánh xạ mã lỗi (library bảo mật → mã API) và mã HTTP. Thuần, testable.
 * Không bao giờ map sang thông điệp chứa chi tiết nội bộ/provider.
 */

export const SETTINGS_HTTP_STATUS: Record<string, number> = {
  AI_SETTINGS_DISABLED: 404,
  AI_CSRF_REJECTED: 403,
  AI_RATE_LIMITED: 429,
  AI_INPUT_INVALID: 422,
  AI_URL_REJECTED: 422,
  AI_DNS_REJECTED: 422,
  AI_REDIRECT_REJECTED: 422,
  AI_VERSION_CONFLICT: 409,
  AI_CONFIG_NOT_VERIFIED: 409,
  AI_CONFIG_NOT_FOUND: 404,
  AI_JOB_NOT_FOUND: 404,
  AI_DECRYPT_FAILED: 500,
  AI_CONFIG_REQUIRED: 503,
  AI_DISABLED: 503,
  AI_OUTBOUND_FAILED: 502,
  AI_TEST_FAILED: 502,
  AI_PROVIDER_TIMEOUT: 504,
  AI_RESULT_TOO_LARGE: 413,
  AI_INTERNAL: 500,
};

const LIBRARY_TO_API: Record<string, string> = {
  INVALID_INPUT: "AI_INPUT_INVALID",
  CONFIGURATION: "AI_CONFIG_REQUIRED",
  ENVELOPE_INVALID: "AI_DECRYPT_FAILED",
  DECRYPT_FAILED: "AI_DECRYPT_FAILED",
  URL_REJECTED: "AI_URL_REJECTED",
  DNS_REJECTED: "AI_DNS_REJECTED",
  REDIRECT_REJECTED: "AI_REDIRECT_REJECTED",
  OUTBOUND_FAILED: "AI_OUTBOUND_FAILED",
  TIMEOUT: "AI_PROVIDER_TIMEOUT",
  RESPONSE_TOO_LARGE: "AI_RESULT_TOO_LARGE",
  REQUEST_TOO_LARGE: "AI_RESULT_TOO_LARGE",
  NOT_FOUND: "AI_CONFIG_NOT_FOUND",
  VERSION_CONFLICT: "AI_VERSION_CONFLICT",
  NOT_VERIFIED: "AI_CONFIG_NOT_VERIFIED",
  SETTINGS_DISABLED: "AI_SETTINGS_DISABLED",
  TEST_FAILED: "AI_TEST_FAILED",
  RATE_LIMITED: "AI_RATE_LIMITED",
  CSRF_REJECTED: "AI_CSRF_REJECTED",
};

/** Mã API ổn định cho client; mã lạ ⇒ AI_INTERNAL (không rò mã nội bộ). */
export function toApiCode(code: unknown): string {
  if (typeof code !== "string" || code.length === 0) return "AI_INTERNAL";
  if (code.startsWith("AI_")) return code;
  return LIBRARY_TO_API[code] ?? "AI_INTERNAL";
}

export function httpStatusFor(code: string): number {
  return SETTINGS_HTTP_STATUS[code] ?? 500;
}
